import { css } from 'lit';

export const inputStyles = css`
    input {
        background-color: rgb(244, 245, 247);
        border-bottom-color: rgb(244, 245, 247);
        border-bottom-left-radius: 3px;
        border-bottom-right-radius: 3px;
        border-bottom-style: solid;
        border-bottom-width: 1px;
        border-image-outset: 0px;
        border-image-repeat: stretch;
        border-image-slice: 100%;
        border-image-source: none;
        border-image-width: 1;
        border-left-color: rgb(244, 245, 247);
        border-left-style: solid;
        border-left-width: 1px;
        border-right-color: rgb(244, 245, 247);
        border-right-style: solid;
        border-right-width: 1px;
        border-top-color: rgb(244, 245, 247);
        border-top-left-radius: 3px;
        border-top-right-radius: 3px;
        border-top-style: solid;
        border-top-width: 1px;
        box-sizing: border-box;
        color: rgb(10, 10, 10);
        cursor: text;
        display: inline-block;
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
        font-size: 16px;
        font-stretch: 100%;
        font-style: normal;
        font-variant-caps: normal;
        font-variant-east-asian: normal;
        font-variant-ligatures: normal;
        font-variant-numeric: normal;
        font-weight: 400;
        height: 42px;
        letter-spacing: normal;
        line-height: 24px;
        margin-bottom: 5px;
        margin-left: 5px;
        margin-right: 5px;
        margin-top: 5px;
        outline-color: rgb(10, 10, 10);
        outline-style: none;
        outline-width: 0px;
        padding-bottom: 8px;
        padding-left: 8px;
        padding-right: 8px;
        padding-top: 8px;
        text-align: start;
        text-indent: 0px;
        text-rendering: auto;
        text-shadow: none;
        text-size-adjust: 100%;
        text-transform: none;
        transition-delay: 0s;
        transition-duration: 0.1s;
        transition-property: all;
        transition-timing-function: cubic-bezier(0.17, 0.67, 0.5, 0.71);
        width: 300px;
        word-spacing: 0px;
        writing-mode: horizontal-tb;
        -webkit-appearance: none;
        -webkit-rtl-ordering: logical;
        -webkit-border-image: none;
    }

    input:focus {
        background-color: rgb(255, 255, 255);
        border-bottom-color: #24d1db;
        border-bottom-left-radius: 3px;
        border-bottom-right-radius: 3px;
        border-bottom-style: solid;
        border-bottom-width: 1px;
        border-image-outset: 0px;
        border-image-repeat: stretch;
        border-image-slice: 100%;
        border-image-source: none;
        border-image-width: 1;
        border-left-color: #24d1db;
        border-left-style: solid;
        border-left-width: 1px;
        border-right-color: #24d1db;
        border-right-style: solid;
        border-right-width: 1px;
        border-top-color: #24d1db;
        border-top-left-radius: 3px;
        border-top-right-radius: 3px;
        border-top-style: solid;
        border-top-width: 1px;
        box-shadow: #24d1db 1px 1px 0px 0px;
        box-sizing: border-box;
        color: rgb(10, 10, 10);
        cursor: text;
        display: inline-block;
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
        font-size: 16px;
        font-stretch: 100%;
        font-style: normal;
        font-variant-caps: normal;
        font-variant-east-asian: normal;
        font-variant-ligatures: normal;
        font-variant-numeric: normal;
        font-weight: 400;
        height: 42px;
        letter-spacing: normal;
        line-height: 24px;
        outline-color: rgb(10, 10, 10);
        outline-offset: 0px;
        outline-style: none;
        outline-width: 0px;
        padding-bottom: 8px;
        padding-left: 8px;
        padding-right: 8px;
        padding-top: 8px;
        text-align: start;
        text-indent: 0px;
        text-rendering: auto;
        text-shadow: none;
        text-size-adjust: 100%;
        text-transform: none;
        transition-delay: 0s;
        transition-duration: 0.1s;
        transition-property: all;
        transition-timing-function: cubic-bezier(0.17, 0.67, 0.5, 0.71);
        word-spacing: 0px;
        writing-mode: horizontal-tb;
        -webkit-appearance: none;
        -webkit-rtl-ordering: logical;
        -webkit-border-image: none;
    }
`;